### ISSUE TITLE
希望支持微信未安装时  默认微信自己的短信登录

### ISSUE THREAD

**Issue by wscqs** [starboychina/WechatKit#11]
希望支持微信未安装时  默认微信自己的短信登录

**Comment by starboychina** [comment]
没太明白什么意思,
你是想说,没装微信的时候.
给自己的微信发个消息,
然后回到 app 上输入那个消息来注册账号么(模拟手机注册).

这个恐怕无法实现.没装微信的话,生成个二维码倒是可以的. 通过另一部手机扫描这个二维码,来注册.
但是这样做有必要么?
而且这样的话,可以偷用别人手机注册,无法保证个人隐私以及信息安全.
不推荐这么做.

**Comment by wscqs** [comment]
微信 登录时，用户没有安装  微信，  你的代码实现只有：  返回错误回调。           我是希望，用户没有安装微信的时候，出现微信登录的web页面。

**Comment by starboychina** [comment]
很早以前,微信就已经不支持 web 登录了,最多出现一个二维码

**Comment by wscqs** [comment]
没，接口还在，就是WXApi.sendAuthReq(req, viewController: self, delegate: WXApiManager.share)  。  是出现web页面，然后用手机号登录。     因为我应用只能微信登录，所以：必须留下微信未安装时能登录（不然  审核被拒）

**Comment by starboychina** [comment]
你可以试一下, 不止微信的, qq 的不安装客户端, 都是无法使用 web 登录的, 或弹出一个 web 提示 安装客户端.

通过appstore审核的办法就是, 除了微信注册以外, 添加游客, 或者 email 注册,或者手机注册.

**Comment by wscqs** [comment]
额。  我中午已经实现好了。   是希望加入此功能。    https://www.zhihu.com/question/34080893/answer/62922691   这里面有微信的手机号登录图

**Comment by starboychina** [comment]
这个框架,没屏蔽既有接口,

你直接调用你上面说的
WXApi.sendAuthReq(req, viewController: self, delegate: WXApiManager.share) 
就好了

**Comment by wscqs** [comment]
我知道啊。  意思我如果需要这个接口，  那你的框架 就不适用了。

**Comment by starboychina** [comment]
你也可以吧你改过的代码 push request 过来

**Comment by wscqs** [comment]
我改的是：   我把集成你的框架去掉了，集成原生了，  😢

**Comment by starboychina** [comment]
好吧, 我暂时没什么时间去做, 等我忙完,再去做

**Comment by Xinguang** [comment]
19e3f599dcb4402b2e527dda82c6889f60c82a1c

已添加.
