### ISSUE TITLE
无法获取openid

### ISSUE THREAD

**Issue by lifenglibao** [starboychina/WechatKit#12]
通过WechatManager.openid获取openid一直为nil，但是在WechatManager类里面打印WechatManager.openid则不为空，怎么回事

**Comment by Xinguang** [comment]
可能你并没有调用过WechatManager.sharedInstance.checkAuth(),
目前, 没有调用过WechatManager.sharedInstance的话. openid 不会被初始化, 
不推荐直接读取WechatManager.openid,
而是使用checkAuth回调以后, 返回的[String: String]中的openid(https://github.com/starboychina/WechatKit#usage)

下一版本将修复这个问题(将去掉 openid, accessToken, refreshToken 的 static 修饰符)
