### ISSUE TITLE
Type WechatManager has no member shared 

### ISSUE THREAD

**Issue by raisezhang** [starboychina/WechatKit#13]
RT 
这个会是啥问题   多谢啦~   

运行 Demo 也是同样的错误    shared 貌似在代码里面就没有看到

**Comment by Xinguang** [comment]
shared 在这里
https://github.com/starboychina/WechatKit/blob/master/WechatKit/WechatManager.swift#L56

你有可能没有编译框架,
demo 也需要运行 carthage update 或者 pod install 以后才能运行

**Comment by raisezhang** [comment]
我看了好像是我用的版本不对？      pod 'WechatKit'  默认下载的版本不是 master 最新的     看 info.plist  版本是 0.2.4
目前在下载指定版本  pod 'WechatKit', '0.3.1'     发现一直报错， 现在苦逼重装 cocopods 中...   全是泪啊  。。。。  

是这样的问题么？    你说的编译已经编译过了

**Comment by Xinguang** [comment]
0.2.4 也可以用, 但名字会有一些出入, 从 0.3 开始, 命名向 swift3 的风格靠拢了

看样应该是你的 pod 有问题.

如果你的项目是 swift 的, 那我推荐你用 carthage.

**Comment by raisezhang** [comment]
重新安装 ok 了， 多谢 @starboychina
