### ISSUE TITLE
关于微信ipad登录问题

### ISSUE THREAD

**Issue by 903669695** [starboychina/WechatKit#17]
你说ipad上登录，是手机号和隐藏两种，但是陌陌这个app装在ipad上，然后打开陌陌选择微信登录陌陌，拉起的微信会显示一个二维码，要扫描二维码完成陌陌登录，想问个问题，这种你遇到过吗，这个功能是微信sdk实现的吗

**Comment by Xinguang** [comment]
这个是 微信的策略, 官方没有说明, 我在我的ipad模拟器上 运行 demo 的时候, 是可以弹出 输入手机号码的页面.
不会弹出二维码.
估计弹出二维码的, 使用的是 微信 js 方式.(网页登录微信需要扫描 二维码)
https://www.zhihu.com/question/34080893

**Comment by 903669695** [comment]
弹出手机号登录的话，ipad是没有手机卡的，所以你输入手机号也接收不到短信，所以用手机号ipad如何登录微信呢

**Comment by Xinguang** [comment]
ipad 弹出那个画面, 是要给你手机发短信. 手机上认证通过了. (得到一个URL), 在 ipad 上打开那个 URL. 就会弹回你的 APP.

**Comment by 903669695** [comment]
那陌陌那种在ipad上微信登录弹出二维码的方式sdk里有这样的接口吗，我确实在网站接入微信登录有js的方式，但是客户端没找到

**Comment by Xinguang** [comment]
javascript sdk 的话, 那个和 ios sdk 就没关系了.

https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140842
