### ISSUE TITLE
Support Xcode 10 new build system

### ISSUE THREAD

**Issue by atrbx5** [starboychina/WechatKit#21]
have issue with Xcode 10 beta 2

:-1: Multiple commands produce '/Users/*/Library/Developer/Xcode/DerivedData/*-cxldsjycvdwqogglttmoyozcxckq/Build/Products/Debug-iphonesimulator/WechatKit/WechatKit.framework/Info.plist':
1) Target 'WechatKit' has copy command from '/Users/*/Xcode/*/Pods/WechatKit/WechatKit/Info.plist' to '/Users/*/Library/Developer/Xcode/DerivedData/*-cxldsjycvdwqogglttmoyozcxckq/Build/Products/Debug-iphonesimulator/WechatKit/WechatKit.framework/Info.plist'
2) Target 'WechatKit' has process command with input '/Users/*/Xcode/*/*/Pods/Target Support Files/WechatKit/Info.plist'

**Comment by Xinguang** [comment]
fixed it.

> I recommend using Carthage.
