### ISSUE TITLE
为什么不直接依赖 WechatOpenSDK？

### ISSUE THREAD

**Issue by rakuyoMo** [starboychina/WechatKit#23]
想请教一下，为什么不支持依赖 WechatOpenSDK。

我现在也是想用 Swift 做 Wechat 的封装，但是没找到依赖 WechatOpenSDK 的办法，推库会报错。

所以想请教下作者是否在这方面有什么结论？

**Comment by Xinguang** [comment]
首先, WechatKit 可以不依赖 cocoapods, 使用 Carthage(推荐使用Carthage.https://github.com/Carthage/Carthage)

其次 WechatKit 使用  Alamofire 的`Result` 封装了一层.
使用的时候, 可以不考虑异常处理. (根据业务需求而定)

使用 WechatKit 更容易上手.

官方的 WechatOpenSDK, 是在 WechatKit 诞生以后, 将近 2 年才在 cocoapods 上官方维护的.
之前 官方只提供 .a 文件, 当时 cocoapds 有上无数个, 个人维护的WechatOpenSDK, 版本也不是随时更新.

如果你只用 cocoapods .  你可以使用 WechatOpenSDK,  但是 WechatKit 使用 `Result` 的方式, 也值得推荐你尝试一下.

**Comment by rakuyoMo** [comment]
> 首先, WechatKit 可以不依赖 cocoapods, 使用 Carthage(推荐使用Carthage.https://github.com/Carthage/Carthage)
> 
> 其次 WechatKit 使用 Alamofire 的`Result` 封装了一层.
> 使用的时候, 可以不考虑异常处理. (根据业务需求而定)
> 
> 使用 WechatKit 更容易上手.
> 
> 官方的 WechatOpenSDK, 是在 WechatKit 诞生以后, 将近 2 年才在 cocoapods 上官方维护的.
> 之前 官方只提供 .a 文件, 当时 cocoapds 有上无数个, 个人维护的WechatOpenSDK, 版本也不是随时更新.
> 
> 如果你只用 cocoapods . 你可以使用 WechatOpenSDK, 但是 WechatKit 使用 `Result` 的方式, 也值得推荐你尝试一下.

我不是说为什么不使用 WechatOpenSDK 而是使用 WechatKit 😂

我原本的意思是为什么 WechatKit 中以 `.a` 的形式集成 WeChat，而不是依赖 WechatOpenSDK。

我原本以为你这么做的原因会是和我一样，遇到了一些技术问题，因为我自己在依赖 WechatOpenSDK 的时候，出了一些问题... 导致我无法依赖 WechatOpenSDK 封装一个 Pods

因为看到你也没有依赖 WechatOpenSDK， 所以我才想提这个 issus，看看能不能和作者讨论一下

**Comment by Xinguang** [comment]
使用 cocoapods 的 WechatOpenSDK, 就不能用 Carthage 了,  或者,  需要两个都集成.

**Comment by rakuyoMo** [comment]
> 使用 cocoapods 的 WechatOpenSDK, 就不能用 Carthage 了, 或者, 需要两个都集成.

恩恩，我现在已经明白你为什么用 .a 了。

我是尝试用 cocoapods 封装 WechatOpenSDK。然后发现在 pods 检查的时候编译不过... 我对 Carthage 没什么想法

我查到的所有对 微信 SDK 的二次封装都没有依赖 WechatOpenSDK，大家都是两年前甚至更早之前封装的，那个时候还没有 WechatOpenSDK ...
