### ISSUE TITLE
xcode 7.2.1 (7C1002) 会有警告信息

### ISSUE THREAD

**Issue by lukedesu** [starboychina/WechatKit#4]
如下：
Warning: no rule to process file '/Users/exterry/Dropbox/Apps/mydemoapp/Pods/WechatKit/SDKExport/libWeChatSDK.a' of type archive.ar for architecture arm64

Warning: no rule to process file '/Users/exterry/Dropbox/Apps/mydemoapp/Pods/WechatKit/SDKExport/read_me.txt' of type text for architecture arm64

**Comment by Xinguang** [comment]
非常抱歉. pod的配置文件中,代码文件指定为\* 即所有文件.
改为*.h *.swift 以后将不会出现该警告.
下一版本中将会改进该配置文件.

如果你非常介意警告的话.可以使用carthage 来引入框架. 那样将不会出现警告.
