### ISSUE TITLE
更新CocoaPods到1.0.1后出现编译错误

### ISSUE THREAD

**Issue by lukedesu** [starboychina/WechatKit#7]
hi @starboychina ，
我今天把CocoaPods更新到1.0.1后发现会出现如下编译错误：

```
'WechatKit/WechatKit.h' file not found
Could not build Objective-C module 'WechatKit'
```

而在此之前都是好好的，不知道是什么原因导致的

![screen shot 2016-06-03 at 10 25 59 am](https://cloud.githubusercontent.com/assets/128367/15766875/bd990874-2975-11e6-8352-63617197b7c7.png)

**Comment by lukedesu** [comment]
ok 我发现是我的错误 cocoapod更新后需要去缓存
sorry 忽略吧 ~

```
Press Cmd + option + shift + k to clean your build folder
Run pod install
```

**Comment by starboychina** [comment]
对 pod 升级需要 Option-Shift-Command-K 

我新建了 swift 的项目 和 oc 的项目都没出现该问题.

还有 推荐你使用WechatKit最新版
微信 SDK 升级到了1.7 
如果不升级的话 有被 appstore 拒的风险
